name: Deploy todo app to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
  HOSTNAME: ${{secrets.EC2_HOST}}
  USER_NAME: ${{secrets.EC2_USERNAME}}
  REGION: ${{secrets.EC2_REGION}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List files
        run: ls -al
      - name: SSH into EC2 & Install nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{  env.USER_NAME }}
          key: ${{ env.PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install nginx -y
            sudo systemctl start nginx
            sudo systemctl enable nginx
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{  env.USER_NAME }}
          key: ${{ env.PRIVATE_KEY }}
          port: 22
          source: "index.html,style/*,js/*"
          target: "/var/www"
      # - name: SSH into EC2
      #   run:  |
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
      # - name: Clone git
      #   run: git clone https://github.com/pranshu1402/todoApp.git
      # - name: Install node
      #   run: sudo apt-get update 
      # - name: Install Serve
      #   run: npm install --global serve
        
